"""campo estado

Revision ID: 6bfbf4320929
Revises: f6ddd3026e95
Create Date: 2023-01-24 00:31:26.389928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bfbf4320929'
down_revision = 'f6ddd3026e95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Categorias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.Boolean(), nullable=True))

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('estado')

    with op.batch_alter_table('Categorias', schema=None) as batch_op:
        batch_op.drop_column('estado')

    # ### end Alembic commands ###
