"""ususarios

Revision ID: 8710d217de32
Revises: ae239eb8a457
Create Date: 2023-01-29 17:59:11.464846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8710d217de32'
down_revision = 'ae239eb8a457'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombres', sa.String(length=200), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('imagen', sa.Text(), nullable=True),
    sa.Column('contaseña', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    # ### end Alembic commands ###
